### ISSUE TITLE
Window box pops up

### ISSUE THREAD

**Issue by buttsauce777** [Elstinko/Elstinko-s-Minecraft-Fish-Bot#1]
https://imgur.com/a/lJXYyWO

This box pops-up after the 1st run of the program. Please help.

**Comment by Elstinko** [comment]
Haven’t seen that one before. Looks like you might just need to run the program as an administrator.

**Comment by buttsauce777** [comment]
It's same running as an administrator

**Comment by Elstinko** [comment]
Does this happen as soon as you launch the application?  Also, What OS are you running?  Looks like Windows 10 but just to be sure.  I will do my best to replicate the issue but cannot guarantee results.

**Comment by buttsauce777** [comment]
I tried to reinstall my anti-virus software and now the problem is solved. Thanks for the help.　:)
